<script type="text/javascript">
var allLinks = document.getElementById("JPAllLinks");
allLinks.innerHTML =
    "<br/>"
    +"<p>You also like know about:</p>"
    +"<ul>"
    +"<li><a href='http://techprogrammings.blogspot.in/2016/04/angular-js-advanced-trick-and-techniques-javascript.html' target='_blank'> AngularJS advanced trick and techniques </a></li>"
    +"<li><a href='http://techprogrammings.blogspot.in/2016/04/input-form-validation-restrict-input-to-allow-only-required-value.html' target='_blank'> Restrict input to allow only required value (jQuery plugin for input type validation)</a></li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2016/06/form-input-validation-independent-on-full-site-any-where.html' target='_blank'> Automatic Form Input Validation for complete site </a> </li>"
    +"<li><a href='http://techprogrammings.blogspot.in/2015/06/ways-in-javascript-to-create-function.html' target='_blank'> Number of ways you can create function in JavaScript +what are they called</a></li>"
    +"<li><a href='http://techprogrammings.blogspot.in/2015/06/javascript-9-native-object-constructors.html' target='_blank'> JavaScript Native objects</a></li>"
    +"<li><a href='http://techprogrammings.blogspot.in/2015/06/private-functions-and-variables-in-JavaScript.html' target='_blank'> How to Create private function in JavaScrip</a></li>"
    +"<li><a href='http://techprogrammings.blogspot.in/2015/06/javascript-function-as-object.html' target='_blank'> functions as first class object in JavaScript</a></li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2015/03/object-oriented-programming-in-JavaScript-Class-in-JavaScript.html' target='_blank'> Object Oriented concept in JavaScript</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2015/07/advanced-javascript-questions-answers-interview.html' target='_blank'>Advanced JavaScript questions</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2015/07/way-to-declare-global-variables-in-JavaScript.html' target='_blank'>One good way to declare Global Variables in JavaScript</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2015/10/how-to-align-elements-in-row-with-equal-space-around-and-flexible-to-adjust-for-all-window-width-using-diplay-flex.html' target='_blank'>how to align elements in a row with equal space around</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2015/06/closures-in-javascript.html' target='_blank'>Closures in JavaScript</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2015/06/ajax-in-angularjs-for-cross-domain-service-jsonp.html' target='_blank'>AJAX call in AngularJS for cross domain service using JSONP</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2014/06/Cross-Site-Scripting-in-WCF-Web-Service.-How-to-use-AJAX-in-JavaScript-to-get-JSON-from-WCF-in-C-sharp-.net.html' target='_blank'>Cross Site Scripting in WCF Web Service. How to use AJAX in JavaScript to Get/Consume JSON from WCF in C# </a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2016/01/how-to-add-angularjs-in-rails-application-rails-undefined-method-registerengine-for-nill-class-NoMethodError.html' target='_blank'> How to add AngularJS in rails application </a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2016/04/git-hub-configuration-git-hub-setup-git-branch-clone.html' target='_blank'> Git configuration all about </a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2013/07/pass-xml-file-in-stored-procedure-as.html' target='_blank'>Pass XML file in stored procedure as a input parameter from C#</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2013/07/xml-parser-in-sql-server-t-sql-how-to.html' target='_blank'>XML Parser in SQL Server (T-SQL), How to parse XML in SQL</a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2013/12/wish-your-friend-happy-birthday-or-any-special-moment.html' target='_blank'>Wish your friend with your own words and love </a> </li>"
    +"<li> <a href='http://techprogrammings.blogspot.in/2016/07/create-message-in-hindi-by-typing-in-hinglish-english.html' target='_blank'>Create Message in Hindi by typing in Hinglish</a> </li>"
    +"</ul>"
</script>
